CC	= gcc
CFLAGS	= -Wall
OBJECTS	= example_3.o
OUTPUT	= -o ../../../../bin/example_3

example3: $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) $(OUTPUT)

example_3.o:

.PHONY: clean
clean:
	rm ../../../../bin/example_3 $(OBJECTS)
