CC	= gcc
CFLAGS	= -Wall
OBJECTS	= example_1.o
OUTPUT	= -o ../../../../bin/example_1

example1: $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) $(OUTPUT)

ecample_1.o:

.PHONY: clean
clean:
	rm ../../../../bin/example_1 $(OBJECTS)
