all:
	gcc -Wall -c lab2.c                         # Builds lab2.o 
	gcc -Wall -c revwords.c                     # Builds revwords.o
	gcc -o ../../../bin/lab2 lab2.o revwords.o  # Builds executable 

clean:
	rm -f ../../../bin/lab2 lab2.o revwords.o                # Cleans up 
