CC	= gcc
CFLAGS	= -Wall
OBJECTS	= example_2.o
OUTPUT	= -o ../../../../bin/example_2

example1: $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) $(OUTPUT)

ecample_2.o:

.PHONY: clean
clean:
	rm ../../../../bin/example_2 $(OBJECTS)
