CC	= gcc
CFLAGS	= -Wall -DNDEBUG -g
OBJECTS	= example_7.o
OUTPUT	= -o ../../../../bin/example_7

example7: $(OBJECTS)
	$(CC) $(CFLAGS) $(OUTPUT) $(OBJECTS)
example_7.o:

.PHONY: clean
clean:
	rm ../../../../bin/example_7 $(OBJECTS)
