CC	= gcc
CFLAGS	= -Wall
OBJECTS = example_6.o
OUTPUT	= -o ../../../../bin/example_6

example6: $(OBJECTS)
	$(CC) $(CFLAGS) $(OUTPUT) $(OBJECTS)

example_6.o:

.PHONY:
	clean
clean:
	rm  ../../../../bin/example_6 $(OBJECTS)
