CC	= gcc
CFLAGS	= -Wall
OBJECTS	= example_4.o
OUTPUT	= -o ../../../../bin/example_4

example4: $(OBJECTS)
	$(CC) $(CFLAGS) $(OUTPUT) $(OBJECTS)

example_4.o:

.PHONY: clean
clean:
	rm ../../../../bin/example_4 $(OBJECTS)
