CC	= gcc
CFLAGS	= -Wall
OBJECTS	= example_5.o
OUTPUT	= -o ../../../../bin/example_5

example5b: $(OBJECTS)
	$(CC) $(CFLAGS) $(OUTPUT) $(OBJECTS)

example_5.o:

.PHONY:
	clean
clean:
	rm ../../../../bin/example_5 $(OBJECTS)
